<?php

namespace Merlion;

use Merlion\Type;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class MerlionClassmap
{

    public static function getCollection() : \Phpro\SoapClient\Soap\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection([
            new ClassMap('helloWorld', Type\HelloWorld::class),
            new ClassMap('helloWorldResponse', Type\HelloWorldResponse::class),
            new ClassMap('getCatalog', Type\GetCatalog::class),
            new ClassMap('CatalogResult', Type\CatalogResult::class),
            new ClassMap('ArrayOfCatalogResult', Type\ArrayOfCatalogResult::class),
            new ClassMap('getCatalogResponse', Type\GetCatalogResponse::class),
            new ClassMap('ArrayOfString', Type\ArrayOfString::class),
            new ClassMap('getItems', Type\GetItems::class),
            new ClassMap('ItemsResult', Type\ItemsResult::class),
            new ClassMap('ArrayOfItemsResult', Type\ArrayOfItemsResult::class),
            new ClassMap('getItemsResponse', Type\GetItemsResponse::class),
            new ClassMap('getItemsAvail', Type\GetItemsAvail::class),
            new ClassMap('ItemsAvailResult', Type\ItemsAvailResult::class),
            new ClassMap('ArrayOfItemsAvailResult', Type\ArrayOfItemsAvailResult::class),
            new ClassMap('getItemsAvailResponse', Type\GetItemsAvailResponse::class),
            new ClassMap('getShipmentDates', Type\GetShipmentDates::class),
            new ClassMap('ShipmentDatesResult', Type\ShipmentDatesResult::class),
            new ClassMap('ArrayOfShipmentDatesResult', Type\ArrayOfShipmentDatesResult::class),
            new ClassMap('getShipmentDatesResponse', Type\GetShipmentDatesResponse::class),
            new ClassMap('getShipmentMethods', Type\GetShipmentMethods::class),
            new ClassMap('ShipmentMethodsResult', Type\ShipmentMethodsResult::class),
            new ClassMap('ArrayOfShipmentMethodsResult', Type\ArrayOfShipmentMethodsResult::class),
            new ClassMap('getShipmentMethodsResponse', Type\GetShipmentMethodsResponse::class),
            new ClassMap('getCommandResult', Type\GetCommandResult::class),
            new ClassMap('CommandResult', Type\CommandResult::class),
            new ClassMap('ArrayOfCommandResult', Type\ArrayOfCommandResult::class),
            new ClassMap('getCommandResultResponse', Type\GetCommandResultResponse::class),
            new ClassMap('getCommandResultDetails', Type\GetCommandResultDetails::class),
            new ClassMap('getCommandResultDetailsResponse', Type\GetCommandResultDetailsResponse::class),
            new ClassMap('setOrderHeaderCommand', Type\SetOrderHeaderCommand::class),
            new ClassMap('setOrderHeaderCommandResponse', Type\SetOrderHeaderCommandResponse::class),
            new ClassMap('setOrderLineCommand', Type\SetOrderLineCommand::class),
            new ClassMap('setOrderLineCommandResponse', Type\SetOrderLineCommandResponse::class),
            new ClassMap('getItemsProperties', Type\GetItemsProperties::class),
            new ClassMap('ItemsPropertiesResult', Type\ItemsPropertiesResult::class),
            new ClassMap('ArrayOfItemsPropertiesResult', Type\ArrayOfItemsPropertiesResult::class),
            new ClassMap('getItemsPropertiesResponse', Type\GetItemsPropertiesResponse::class),
            new ClassMap('getItemsPropertiesSections', Type\GetItemsPropertiesSections::class),
            new ClassMap('ItemsPropertiesSectionsResult', Type\ItemsPropertiesSectionsResult::class),
            new ClassMap('ArrayOfItemsPropertiesSectionsResult', Type\ArrayOfItemsPropertiesSectionsResult::class),
            new ClassMap('getItemsPropertiesSectionsResponse', Type\GetItemsPropertiesSectionsResponse::class),
            new ClassMap('getItemsImages', Type\GetItemsImages::class),
            new ClassMap('ItemsImagesResult', Type\ItemsImagesResult::class),
            new ClassMap('ArrayOfItemsImagesResult', Type\ArrayOfItemsImagesResult::class),
            new ClassMap('getItemsImagesResponse', Type\GetItemsImagesResponse::class),
            new ClassMap('setAddOrderLineCommand', Type\SetAddOrderLineCommand::class),
            new ClassMap('setAddOrderLineCommandResponse', Type\SetAddOrderLineCommandResponse::class),
            new ClassMap('setMoveOrderLineCommand', Type\SetMoveOrderLineCommand::class),
            new ClassMap('setMoveOrderLineCommandResponse', Type\SetMoveOrderLineCommandResponse::class),
            new ClassMap('setDeleteOrderCommand', Type\SetDeleteOrderCommand::class),
            new ClassMap('setDeleteOrderCommandResponse', Type\SetDeleteOrderCommandResponse::class),
            new ClassMap('setSignOrderCommand', Type\SetSignOrderCommand::class),
            new ClassMap('setSignOrderCommandResponse', Type\SetSignOrderCommandResponse::class),
            new ClassMap('unsetSignOrderCommand', Type\UnsetSignOrderCommand::class),
            new ClassMap('unsetSignOrderCommandResponse', Type\UnsetSignOrderCommandResponse::class),
            new ClassMap('getOrdersList', Type\GetOrdersList::class),
            new ClassMap('OrdersListResult', Type\OrdersListResult::class),
            new ClassMap('ArrayOfOrdersListResult', Type\ArrayOfOrdersListResult::class),
            new ClassMap('getOrdersListResponse', Type\GetOrdersListResponse::class),
            new ClassMap('getOrderLines', Type\GetOrderLines::class),
            new ClassMap('OrderLinesResult', Type\OrderLinesResult::class),
            new ClassMap('ArrayOfOrderLinesResult', Type\ArrayOfOrderLinesResult::class),
            new ClassMap('getOrderLinesResponse', Type\GetOrderLinesResponse::class),
            new ClassMap('getOrderLinesGTD', Type\GetOrderLinesGTD::class),
            new ClassMap('OrderLinesGTDResult', Type\OrderLinesGTDResult::class),
            new ClassMap('ArrayOfOrderLinesGTDResult', Type\ArrayOfOrderLinesGTDResult::class),
            new ClassMap('getOrderLinesGTDResponse', Type\GetOrderLinesGTDResponse::class),
            new ClassMap('getCounterAgent', Type\GetCounterAgent::class),
            new ClassMap('DictionaryResult', Type\DictionaryResult::class),
            new ClassMap('ArrayOfDictionaryResult', Type\ArrayOfDictionaryResult::class),
            new ClassMap('getCounterAgentResponse', Type\GetCounterAgentResponse::class),
            new ClassMap('getContracts', Type\GetContracts::class),
            new ClassMap('ContractsResult', Type\ContractsResult::class),
            new ClassMap('ArrayOfContractsResult', Type\ArrayOfContractsResult::class),
            new ClassMap('getContractsResponse', Type\GetContractsResponse::class),
            new ClassMap('getShipmentAgents', Type\GetShipmentAgents::class),
            new ClassMap('getShipmentAgentsResponse', Type\GetShipmentAgentsResponse::class),
            new ClassMap('getRepresentative', Type\GetRepresentative::class),
            new ClassMap('RepresentativeResult', Type\RepresentativeResult::class),
            new ClassMap('ArrayOfRepresentativeResult', Type\ArrayOfRepresentativeResult::class),
            new ClassMap('getRepresentativeResponse', Type\GetRepresentativeResponse::class),
            new ClassMap('getEndPointDelivery', Type\GetEndPointDelivery::class),
            new ClassMap('EndPointDeliveryResult', Type\EndPointDeliveryResult::class),
            new ClassMap('ArrayOfEndPointDeliveryResult', Type\ArrayOfEndPointDeliveryResult::class),
            new ClassMap('getEndPointDeliveryResponse', Type\GetEndPointDeliveryResponse::class),
            new ClassMap('getPackingTypes', Type\GetPackingTypes::class),
            new ClassMap('getPackingTypesResponse', Type\GetPackingTypesResponse::class),
            new ClassMap('getCurrencyRate', Type\GetCurrencyRate::class),
            new ClassMap('CurrencyRateResult', Type\CurrencyRateResult::class),
            new ClassMap('ArrayOfCurrencyRateResult', Type\ArrayOfCurrencyRateResult::class),
            new ClassMap('getCurrencyRateResponse', Type\GetCurrencyRateResponse::class),
            new ClassMap('getCountry', Type\GetCountry::class),
            new ClassMap('getCountryResponse', Type\GetCountryResponse::class),
            new ClassMap('getItemsBarcodes', Type\GetItemsBarcodes::class),
            new ClassMap('ItemsBarcodesResult', Type\ItemsBarcodesResult::class),
            new ClassMap('ArrayOfItemsBarcodesResult', Type\ArrayOfItemsBarcodesResult::class),
            new ClassMap('getItemsBarcodesResponse', Type\GetItemsBarcodesResponse::class),
            new ClassMap('getLinkedItems', Type\GetLinkedItems::class),
            new ClassMap('LinkedItemsResult', Type\LinkedItemsResult::class),
            new ClassMap('ArrayOfLinkedItemsResult', Type\ArrayOfLinkedItemsResult::class),
            new ClassMap('getLinkedItemsResponse', Type\GetLinkedItemsResponse::class),
            new ClassMap('setLinkedItems', Type\SetLinkedItems::class),
            new ClassMap('setLinkedItemsResponse', Type\SetLinkedItemsResponse::class),
        ]);
    }


}

